version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/var/www
    depends_on:
      - app-mysql
      - app-redis
  app-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: productapp
      MYSQL_ROOT_PASSWORD: root

  app-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app

  app-redis:
    image: redis:alpine
    expose:
      - 6379
